name: Build and Push Image

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build Docker image
        run: |
          IMAGE=ghcr.io/syogesh26/fusionfact:latest
          docker build -t $IMAGE .

      - name: Login to GitHub Repo
        run: |
          echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Push Image
        run: docker push $IMAGE

      
